language: node_js

node_js:
  - '12'
  - '10'
  - '9'
  - '8'

after_success:
  - npm run build
  - npx travis-deploy-once "npm run semantic-release"
  - npm run test:coveralls

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

sudo: false
